# permissions for end users to view renginecontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: renginecontroller-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rengine-operator
    app.kubernetes.io/part-of: rengine-operator
    app.kubernetes.io/managed-by: kustomize
  name: renginecontroller-viewer-role
rules:
- apiGroups:
  - rengine.wl4g.com
  resources:
  - renginecontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rengine.wl4g.com
  resources:
  - renginecontrollers/status
  verbs:
  - get
