# permissions for end users to edit rengineexecutors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rengineexecutor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rengine-operator
    app.kubernetes.io/part-of: rengine-operator
    app.kubernetes.io/managed-by: kustomize
  name: rengineexecutor-editor-role
rules:
- apiGroups:
  - rengine.wl4g.com
  resources:
  - rengineexecutors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rengine.wl4g.com
  resources:
  - rengineexecutors/status
  verbs:
  - get
